<!DOCTYPE casa
[
<!ELEMENT casa (habitacion+,objeto+,servicios?,disponibilidad?,animales*)>
<!ELEMENT habitacion (#PCDATA)>
<!ELEMENT objeto (#PCDATA)> 
<!ELEMENT servicios (#PCDATA)> 
<!ELEMENT disponibilidad EMPTY> 
<!ELEMENT animales (#PCDATA)> 

<!ATTLIST objeto nombre CDATA #REQUIRED>
<!ATTLIST disponibilidad estado (si|no) #REQUIRED>
<!ATTLIST animales tipo CDATA #REQUIRED>
]>

<casa>
  <habitacion>COMEDOR</habitacion>
  <habitacion>SALA DE ESTAR</habitacion>
  <habitacion>DORMITORIO I</habitacion>
  <habitacion>DORMITORIO II</habitacion>
  <objeto nombre="ventana"/>
  <disponibilidad estado="no"/>
  <animales tipo="perro">SOLOVINO</animales>
  <animales tipo="gato">NUBE</animales>
  <animales tipo="cocodrilo">PEJELAGARTO</animales>"
</casa>
