<!DOCTYPE CASA
[
	<!ELEMENT CASA (CUARTO,BAÑO,SALA)+>
	<!ELEMENT CUARTO (#PCDATA,BURÓ)>
		<!ELEMENT BURÓ (#PCDATA)>
	<!ELEMENT BAÑO (#PCDATA,TAZA)>
		<!ELEMENT TAZA (#PCDATA)>
	<!ELEMENT SALA (#PCDATA)>
]>


<!--CASA-->
<CASA>
	<CUARTO>
		MI HERMANO ESTA ACOSTADO
		<BURÓ>AQUI ESTA UN RELOJ</BURÓ>
	</CUARTO>
	<BAÑO>
		DENTRO DEL BAÑO TAMBIÉN ESTÁ LA REGADERA
		<TAZA></TAZA>
	</BAÑO>
	<SALA>
		MI MAMÁ ESTÁ LEYENDO
	</SALA>
</CASA>