<!DOCTYPE AUTOMOVIL
[
	<!ELEMENT AUTOMOVIL (CAJUELA?,ASIENTO+,ESPEJO+,LLANTA+)>
		<!ELEMENT CAJUELA (#PCDATA,LLANTA)>
			<!ELEMENT LLANTA (#PCDATA)>
		<!ELEMENT ASIENTO (#PCDATA)>
		<!ELEMENT ESPEJO (#PCDATA)>
		<!ELEMENT LLANTA (#PCDATA)>
]>

<AUTOMOVIL>
	<CAJUELA>
		PODEMOS GUARDAR LA DESPENSA
		<LLANTA>
			PUEDE ESTAR UNA O M√ÅS LLANTAS DE REPUESTO
		</LLANTA>
	</CAJUELA>
	<ASIENTO>
		AQUI ES PARA QUE UNA PERSONA SE SIENTE
	</ASIENTO>
	<ESPEJO></ESPEJO>
	<LLANTA></LLANTA>
</AUTOMOVIL>