<!DOCTYPE RAIZ
[
	<!ELEMENT RAIZ (#PCDATA,DATOS,DIRECCION,TELEFONO?,CELULAR,RAZA)>
		<!ELEMENT DATOS (NOMBRE+,APELLIDO+)>
			<!ELEMENT NOMBRE (#PCDATA)>
			<!ELEMENT APELLIDO (#PCDATA)>
		<!ELEMENT DIRECCION (#PCDATA)>
		<!ELEMENT TELEFONO (#PCDATA)>
		<!ELEMENT CELULAR (#PCDATA)>
		<!ELEMENT RAZA ANY> 
]>

<RAIZ>
	ANOTE SUS DATOS CORRESPONDIENTES
	<DATOS>
		<NOMBRE>JESUS</NOMBRE>
		<APELLIDO>DIAZ</APELLIDO>
	</DATOS>
	<DIRECCION>AVENIDA HIDALGO</DIRECCION>
	<TELEFONO>26697315</TELEFONO>
	<CELULAR></CELULAR>
	<RAZA />
</RAIZ>